### ISSUE TITLE
tcpoverty fails after update (Possible bug?)

### ISSUE THREAD

**Issue by Thirdhuman** [PSLmodels/Tax-Calculator#2303]
[evtedeschi3's "Code for Analysis of Poverty Using Tax-Calculator"](https://github.com/evtedeschi3/tcpoverty)

Using the latest version of Tax Calc (2.0), the tcpoverty script [tcpov2b_make_tc_file.do](https://github.com/evtedeschi3/tcpoverty/blob/master/tcpov2b_make_tc_file.do) fails.  

**The following command returns a value error:**
`./taxcalc.sh c17_taxsim save`

**Error output:**
```
Traceback (most recent call last):
  File "/anaconda3/bin/tc", line 11, in <module>
    sys.exit(cli_tc_main())
  File "/anaconda3/lib/python3.6/site-packages/taxcalc/cli/tc.py", line 160, in cli_tc_main
    exact_calculations=args.exact)
  File "/anaconda3/lib/python3.6/site-packages/taxcalc/taxcalcio.py", line 335, in init
    start_year=tax_year)
  File "/anaconda3/lib/python3.6/site-packages/taxcalc/records.py", line 148, in __init__
    raise ValueError(msg)
ValueError: expression "e00600 >= e00650" is not true for every record
ERROR: taxcalc package is not available
```

Did the tax-calc 2.0 update cause a bug that is causing evtedeschi3's script to now fail?

**Comment by martinholmer** [comment]
@Thirdhuman asked in issue #2303:
> Did the taxcalc 2.0 update cause a bug that is causing evtedeschi3's script to now fail?

I have no idea without being able to replicate your experience.
I can't do that without having a copy of the `c17_taxsim` file being used as tc input.

**Comment by Thirdhuman** [comment]
https://www.dropbox.com/s/lpaw74sqq1n4hsv/c17_taxsim?dl=0

**Comment by martinholmer** [comment]
@Thirdhuman, Thanks for the `c17_taxsim` file.
I'll investigate this afternoon.

**Comment by martinholmer** [comment]
@Thirdhuman,  Using the taxcalc 2.0 package on my computer with the `c17_taxsim` file you provided, I can replicate the errors you reported in Tax-Calculator issue #2303 when executing `./taxcalc.sh c17_taxsim` in the `taxcalc/validation/taxsim` directory.  The key error message is this:
```
ValueError: expression "e00600 >= e00650" is not true for every record
```
When I look at the `c17_taxsim.csv` file generated from the `c17_taxsim` file, I see 352 records out of the total 89,820 records that violate the required condition `e00600 >= e00650`.  It is required because that is what it says in the documentation and that is the way it is on the IRS tax forms.  Here's a screen shot from the Tax-Calculator user documentation:

<img width="1309" alt="Screen Shot 2019-04-16 at 2 30 33 PM" src="https://user-images.githubusercontent.com/12170745/56236002-a00a6300-6056-11e9-8ed1-67e9a9f5dc2e.png">

For example, consider this record (which is one of the 352) where I'm showing only the variables in the `c17_taxsim.csv` file that are non-zero:
```
iMac:taxsim mrh$ ../../../csv_show.sh c17_taxsim.csv 114401
1 RECID 114401
2 FLPDYR 2017
3 age_head 51
5 MARS 1
9 XTOT 1
10 e00200p 80000.0
12 e00200 80000.0
13 e00650 25000.0
14 e00300 89000.0
17 e00600 20000.0
24 e18400 27630
```
This is a violation of the condition that dividends `e00600` be no less than qualified dividends `e00650` because $20,000 is less than $25,000.  Again, from the user documentation:

<img width="750" alt="Screen Shot 2019-04-16 at 2 54 59 PM" src="https://user-images.githubusercontent.com/12170745/56236478-b49b2b00-6057-11e9-8b11-3106e35c7c5e.png">

So, the question becomes how did this individual get those values for dividends and qualified dividends.

We we look at that individual's record in the original `c17_taxsim` file, we see this:
```
iMac:taxsim mrh$ awk '$1==114401' c17_taxsim
114401 2017 33 1 51 0 0 0 0 0 80000 0 25000 89000 0 0 -5000 0 0 0 0 0 -5000 0 27630 0 0
```
Qualified dividends (ivar 10) is $25,000 and other property income subject to NIIT (ivar 17) is -$5,000.  If you look at the `prepare_taxcalc_input.py` code, you'll see the bug.  Here it is:
```
    nonqualified_dividends = ivar.loc[:, 17]
    invar['e00600'] = invar['e00650'] + nonqualified_dividends
```
These two lines work **only** if ivar 17 is non-negative.

**The ivar 17 value in the validation tests is always zero, which is why this hasn't come up before people started using this validation framework to do other things.**

How should the a TAXSIM-27 ivar 17 value be translated into a Tax-Calculator input variable?
I'll have to think about that and change the code in the `prepare_taxcalc_input.py` script.  Clearly dividends cannot be negative, so the current translation is wrong.  Any suggestions?

P.S.  You may be asking your self why didn't this error come up before when I was using taxcalc 1.2?
I don't know.  I tried to find an answer to this question but did not come up with an answer quickly.
I'm going to focus on fixing the `prepare_taxcalc_input.py` script.

@evtedeschi3

**Comment by martinholmer** [comment]
After more investigation, it seems as if the way to fix the bug reported in issue #2303 is to translate TAXSIM-27 ivar 13 (qualified dividends) to Tax-Calculator input variables `e00600` and `e00650` (making those two values equal to the ivar 13 value) and translating ivar 17 ("other property income subject to NIIT") to Tax-Calculator input variable `e02000`.  If I don't hear any objections, I'll prepare a pull request that makes those changes in the coming hours.

@Thirdhuman @evtedeschi3

**Comment by martinholmer** [comment]
The command `./taxcalc.sh c17_taxsim` works with code from the tip of the master branch after pull request #2304 was merged.

@Thirdhuman,  Thanks for the bug report.  Please raise another issue if you continue to have problems.

**Comment by martinholmer** [comment]
@Thirdhuman and @evtedeschi3,  Given the changes in pull request #2306, you will need to update source source code to the tip of the master branch (post merge of #2306) **and** use the taxcalc package for release 2.0.1.  Again, if you have any questions or additional problems, please raise a new issue.
