### ISSUE TITLE
--tables and --graphs arguments causing errors

### ISSUE THREAD

**Issue by aelsibaie** [PSLmodels/Tax-Calculator#2481]
Steps to replicate:

Run `tc cps.csv 2022 --reform ptaxes0.json --graphs` or `tc cps.csv 2022 --reform ptaxes0.json --tables`
with the `ptaxes0.json` containing
```
{
    "FICA_ss_trt": {
        "2021": 0.130,
        "2022": 0.140
    },
    "FICA_mc_trt": {
        "2021": 0.030,
        "2022": 0.032
    }        
}
```

Associated errors:
```
(psl) C:\Users\Amir>tc cps.csv 2022 --reform ptaxes0.json --tables
You loaded data for 2014.
Tax-Calculator startup automatically extrapolated your data to 2022.
Traceback (most recent call last):
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\pandas\core\indexes\base.py", line 2889, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 97, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Amir\miniconda3\envs\psl\Scripts\tc-script.py", line 10, in <module>
    sys.exit(cli_tc_main())
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\taxcalc\cli\tc.py", line 186, in cli_tc_main
    output_sqldb=args.sqldb)
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\taxcalc\taxcalcio.py", line 464, in analyze
    self.write_tables_file()
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\taxcalc\taxcalcio.py", line 546, in write_tables_file
    TaxCalcIO.write_decile_table(distdf, tfile, tkind='Reform Totals')
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\taxcalc\taxcalcio.py", line 591, in write_decile_table
    row += rowfmt.format(rtns_series[decile] * 1e-6,
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\pandas\core\frame.py", line 2902, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\pandas\core\indexes\base.py", line 2891, in get_loc
    raise KeyError(key) from err
KeyError: 0
```
```
(psl) C:\Users\Amir>tc cps.csv 2022 --reform ptaxes0.json --graphs
You loaded data for 2014.
Tax-Calculator startup automatically extrapolated your data to 2022.
Traceback (most recent call last):
  File "C:\Users\Amir\miniconda3\envs\psl\Scripts\tc-script.py", line 10, in <module>
    sys.exit(cli_tc_main())
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\taxcalc\cli\tc.py", line 186, in cli_tc_main
    output_sqldb=args.sqldb)
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\taxcalc\taxcalcio.py", line 470, in analyze
    self.write_graph_files()
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\taxcalc\taxcalcio.py", line 626, in write_graph_files
    fig = self.calc_base.atr_graph(self.calc, pop_quantiles=False)
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\taxcalc\calculator.py", line 965, in atr_graph
    pop_quantiles=pop_quantiles)
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\taxcalc\utils.py", line 1006, in atr_graph_data
    atr1_series[included] = avgtax1_series[included] / avginc_series[included]
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\pandas\core\ops\__init__.py", line 651, in f
    new_data = self._combine_frame(other, na_op, fill_value)
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\pandas\core\frame.py", line 5863, in _combine_frame
    new_data = ops.dispatch_to_series(self, other, _arith_op)
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\pandas\core\ops\__init__.py", line 275, in dispatch_to_series
    bm = left._mgr.operate_blockwise(right._mgr, array_op)
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\pandas\core\internals\managers.py", line 364, in operate_blockwise
    return operate_blockwise(self, other, array_op)
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\pandas\core\internals\ops.py", line 38, in operate_blockwise
    res_values = array_op(lvals, rvals)
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\pandas\core\ops\array_ops.py", line 185, in arithmetic_op
    res_values = op(lvalues, rvalues)
TypeError: unsupported operand type(s) for /: 'Categorical' and 'Categorical'
```

**Comment by Peter-Metz** [comment]
Hi @aelsibaie, thanks for opening this issue. What version of Tax-Calculator are you using? I was able to run your command with Tax-Calculator 3.0.0 without any errors (to update, you can run `conda update -c pslmodels taxcalc`).

**Comment by aelsibaie** [comment]
I should be using the latest version. Unfortunately- I don't have too much more to add with how to reproduce the error, other than a colleague is also having the same problem on another computer. Both Conda and TC were freshly installed and we are running Windows 10. Here is my console after attempting to update and re-run the calculator.
```
(psl) C:\Users\Amir>conda update -c pslmodels taxcalc
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.


(psl) C:\Users\Amir>tc cps.csv 2022 --reform ptaxes0.json --graphs
You loaded data for 2014.
Tax-Calculator startup automatically extrapolated your data to 2022.
Traceback (most recent call last):
  File "C:\Users\Amir\miniconda3\envs\psl\Scripts\tc-script.py", line 10, in <module>
    sys.exit(cli_tc_main())
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\taxcalc\cli\tc.py", line 186, in cli_tc_main
    output_sqldb=args.sqldb)
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\taxcalc\taxcalcio.py", line 470, in analyze
    self.write_graph_files()
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\taxcalc\taxcalcio.py", line 626, in write_graph_files
    fig = self.calc_base.atr_graph(self.calc, pop_quantiles=False)
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\taxcalc\calculator.py", line 965, in atr_graph
    pop_quantiles=pop_quantiles)
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\taxcalc\utils.py", line 1006, in atr_graph_data
    atr1_series[included] = avgtax1_series[included] / avginc_series[included]
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\pandas\core\ops\__init__.py", line 651, in f
    new_data = self._combine_frame(other, na_op, fill_value)
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\pandas\core\frame.py", line 5863, in _combine_frame
    new_data = ops.dispatch_to_series(self, other, _arith_op)
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\pandas\core\ops\__init__.py", line 275, in dispatch_to_series
    bm = left._mgr.operate_blockwise(right._mgr, array_op)
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\pandas\core\internals\managers.py", line 364, in operate_blockwise
    return operate_blockwise(self, other, array_op)
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\pandas\core\internals\ops.py", line 38, in operate_blockwise
    res_values = array_op(lvals, rvals)
  File "C:\Users\Amir\miniconda3\envs\psl\lib\site-packages\pandas\core\ops\array_ops.py", line 185, in arithmetic_op
    res_values = op(lvalues, rvalues)
TypeError: unsupported operand type(s) for /: 'Categorical' and 'Categorical'
```

**Comment by Peter-Metz** [comment]
Would you mind posting the output from `conda list`?

**Comment by aelsibaie** [comment]
```
(psl) C:\Users\Amir>conda list
# packages in environment at C:\Users\Amir\miniconda3\envs\psl:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
bokeh                     2.2.1                    py36_0
brotlipy                  0.7.0           py36he774522_1000
ca-certificates           2020.7.22                     0
certifi                   2020.6.20                py36_0
cffi                      1.14.2           py36h7a1dbc1_0
chardet                   3.0.4                 py36_1003
cryptography              3.1              py36h7a1dbc1_0
freetype                  2.10.2               hd328e21_0
idna                      2.10                       py_0
intel-openmp              2020.2                      254
jinja2                    2.11.2                     py_0
jpeg                      9b                   hb83a4c4_2
libllvm9                  9.0.1                h21ff451_0
libpng                    1.6.37               h2a8f88b_0
libtiff                   4.1.0                h56a325e_1
llvmlite                  0.33.0           py36ha925a31_0
lz4-c                     1.9.2                h62dcd97_1
markupsafe                1.1.1            py36he774522_0
mkl                       2020.2                      256
mkl-service               2.3.0            py36hb782905_0
mkl_fft                   1.1.0            py36h45dec08_0
mkl_random                1.1.1            py36h47e9c7a_0
numba                     0.50.1           py36h47e9c7a_0
numpy                     1.19.1           py36h5510c5b_0
numpy-base                1.19.1           py36ha3acd2a_0
olefile                   0.46                     py36_0
openssl                   1.1.1g               he774522_1
packaging                 20.4                       py_0
pandas                    1.1.1            py36ha925a31_0
pillow                    7.2.0            py36hcc1f983_0
pip                       20.2.2                   py36_0
pycparser                 2.20                       py_2
pyopenssl                 19.1.0                     py_1
pyparsing                 2.4.7                      py_0
pysocks                   1.7.1                    py36_0
python                    3.6.10               h9f7ef89_2
python-dateutil           2.8.1                      py_0
pytz                      2020.1                     py_0
pyyaml                    5.3.1            py36he774522_1
requests                  2.24.0                     py_0
setuptools                49.6.0                   py36_0
six                       1.15.0                     py_0
sqlite                    3.33.0               h2a8f88b_0
taxcalc                   2.9.0                    py36_0    pslmodels
tbb                       2020.2               h74a9793_0
tk                        8.6.10               he774522_0
tornado                   6.0.4            py36he774522_1
typing_extensions         3.7.4.3                    py_0
urllib3                   1.25.10                    py_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
wheel                     0.35.1                     py_0
win_inet_pton             1.1.0                    py36_0
wincertstore              0.2              py36h7fe50ca_0
xz                        5.2.5                h62dcd97_0
yaml                      0.2.5                he774522_0
zlib                      1.2.11               h62dcd97_4
zstd                      1.4.5                h04227a9_0
```

**Comment by aelsibaie** [comment]
Thank you! That has resolved the issue. If this is something you want to look into @Peter-Metz  [these were the docs](https://pslmodels.github.io/Tax-Calculator/usage/starting.html) I used to setup taxcalc which seemed to have installed the incorrect version. Feel free to close this issue if there is something I missed

**Comment by hdoupe** [comment]
Thanks @aelsibaie. @Peter-Metz it seems like we should update this part: https://pslmodels.github.io/Tax-Calculator/usage/starting.html#download-tax-calculator-package

**Comment by Peter-Metz** [comment]
Thanks @hdoupe and @aelsibaie. Just opened #2482 to update the installation instructions. I think we can close this issue since we've resolved the initial problem.
